# Generated by Django 5.0.3 on 2024-05-15 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0009_profile_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='kullanici_tipi',
            field=models.CharField(choices=[('ogretmen', 'Öğretmen'), ('ogrenci', 'Öğrenci'), ('Admin', 'Admin')], max_length=50),
        ),
    ]
