# Generated by Django 5.0.3 on 2024-05-19 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0010_alter_profile_kullanici_tipi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='kullanici_tipi',
            field=models.CharField(choices=[('egitmen', 'Eğitmen'), ('ogrenci', 'Öğrenci')], max_length=50),
        ),
        migrations.CreateModel(
            name='EgitmenProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dersler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Base.ders')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Base.profile')),
            ],
        ),
        migrations.CreateModel(
            name='OgrenciProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seviye', models.CharField(choices=[('ilkokul', 'İlkokul'), ('ortaokul', 'Ortaokul'), ('lise', 'Lise'), ('universite', 'Üniversite'), ('yukseklisans', 'Yüksek Lisans')], max_length=50)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Base.profile')),
            ],
        ),
    ]
