# Generated by Django 5.0.3 on 2024-05-20 21:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0011_alter_profile_kullanici_tipi_egitmenprofile_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='egitmenprofile',
            name='dersler',
        ),
        migrations.AlterField(
            model_name='ogrenciprofile',
            name='profile',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Base.profile'),
        ),
    ]
